# Generated by Django 3.1.1 on 2020-09-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('rut_admin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido_p', models.CharField(max_length=25)),
                ('apellido_m', models.CharField(max_length=25)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.BigIntegerField(primary_key=True, serialize=False)),
                ('revision_refrigerado', models.CharField(max_length=1)),
                ('revision_envasado', models.CharField(max_length=1)),
                ('embalaje', models.CharField(max_length=1)),
                ('conteo', models.BigIntegerField()),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateField()),
                ('detalle_compra', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buque',
            fields=[
                ('id_buque', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_buque', models.CharField(max_length=10)),
                ('puerto_asignado', models.CharField(max_length=10)),
                ('seguro_id_seguro', models.BigIntegerField()),
            ],
            options={
                'db_table': 'buque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido_p', models.CharField(max_length=25)),
                ('apellido_m', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('nombre_empresa', models.CharField(blank=True, max_length=25, null=True)),
                ('tipo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('rut_consul', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido_p', models.CharField(max_length=25)),
                ('apellido_m', models.CharField(max_length=25)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'consultor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoCliente',
            fields=[
                ('id_contrato_cli', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('id_prodtor', models.BigIntegerField()),
            ],
            options={
                'db_table': 'contrato_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ganancia',
            fields=[
                ('id_ganancias', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ganancia_global', models.CharField(max_length=10)),
                ('venta_id_venta', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ganancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('monto', models.BigIntegerField()),
                ('fecha_pago', models.DateField()),
                ('tipo_pago', models.CharField(max_length=20)),
                ('conformidad', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProceVenta',
            fields=[
                ('id_procventa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('costo_transpo', models.BigIntegerField()),
                ('impuesto_aduana', models.BigIntegerField()),
                ('pago_servicio', models.BigIntegerField()),
                ('comision_emp', models.BigIntegerField()),
                ('iva', models.BigIntegerField()),
            ],
            options={
                'db_table': 'proce_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_produ', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('precio', models.BigIntegerField()),
                ('id_procventa', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoDisp',
            fields=[
                ('id_prod_dispo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('precio', models.BigIntegerField()),
                ('cantidad', models.CharField(max_length=3)),
                ('fecha_venci', models.DateField()),
                ('grado_calidad', models.CharField(max_length=25)),
                ('total_valor', models.BigIntegerField()),
                ('id_prodtor', models.BigIntegerField()),
            ],
            options={
                'db_table': 'producto_disp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id_prodtor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_pro', models.CharField(max_length=15)),
                ('nombre_pro', models.CharField(max_length=25)),
                ('apell_p_pro', models.CharField(max_length=25)),
                ('apell_m_pro', models.CharField(max_length=25)),
                ('fono_pro', models.BigIntegerField()),
                ('email_pro', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'productor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoSobrante',
            fields=[
                ('id_sobras', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('cantidad_sobra', models.FloatField()),
            ],
            options={
                'db_table': 'producto_sobrante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('totalidad_reportes', models.BigIntegerField()),
                ('resumen_info', models.CharField(max_length=100)),
                ('estadisticas_reporte', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id_seguro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('gastos', models.BigIntegerField()),
                ('buque_id_buque', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'seguro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_servi', models.CharField(max_length=25)),
                ('costo_servicio', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id_solicitud', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('fruta', models.CharField(max_length=15)),
                ('presupuesto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'solicitud_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transpor',
            fields=[
                ('rut_transport', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apell_p', models.CharField(max_length=25)),
                ('apel_m', models.CharField(max_length=25)),
                ('fono', models.BigIntegerField()),
                ('mail', models.CharField(max_length=25)),
                ('transporte_patente', models.CharField(max_length=6)),
                ('transporte_patente2', models.CharField(max_length=1)),
                ('id_prodtor', models.BigIntegerField()),
            ],
            options={
                'db_table': 'transpor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('capacidacarga', models.FloatField()),
                ('refrigeracion', models.CharField(max_length=1)),
                ('tipo', models.CharField(max_length=25)),
                ('tamanio', models.CharField(max_length=25)),
                ('transta_rut_transta', models.CharField(max_length=10)),
                ('transta_rut_transta2', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_venta', models.CharField(max_length=30)),
                ('fecha_venta', models.DateField()),
                ('total_a_cobrar', models.BigIntegerField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteExterno',
            fields=[
                ('id_cli', models.OneToOneField(db_column='id_cli', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.cliente')),
                ('nie', models.CharField(max_length=25, unique=True)),
                ('demanda', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cliente_externo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteLocal',
            fields=[
                ('id_cli', models.OneToOneField(db_column='id_cli', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.cliente')),
                ('rut_cliente', models.CharField(max_length=25, unique=True)),
                ('presupuesto', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'cliente_local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relation11',
            fields=[
                ('produ_dispo_id_prod_dispo', models.OneToOneField(db_column='produ_dispo_id_prod_dispo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.productodisp')),
            ],
            options={
                'db_table': 'relation_11',
                'managed': False,
            },
        ),
    ]
