# Generated by Django 3.1.1 on 2020-09-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteInterno',
            fields=[
                ('rut_clii', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_clii', models.CharField(max_length=25)),
                ('apellido_clii', models.CharField(max_length=25)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente_interno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComunaLocal',
            fields=[
                ('id_comuna', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'comuna_local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionLocal',
            fields=[
                ('id_direccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'direccion_local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id_fruta', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'fruta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPagoE',
            fields=[
                ('id_metodo_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_pago', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'metodo_pago_e',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPagoL',
            fields=[
                ('id_metodo_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_pago', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'metodo_pago_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoEx',
            fields=[
                ('id_pagoex', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pagoex', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pago_ex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoI',
            fields=[
                ('id_pagoi', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
            ],
            options={
                'db_table': 'pago_i',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoVentaEx',
            fields=[
                ('id_proceso_ex', models.BigAutoField(primary_key=True, serialize=False)),
                ('impuesto_aduana', models.BigIntegerField()),
                ('comision_empresa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'proceso_venta_ex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoVentaLocal',
            fields=[
                ('id_vental', models.BigAutoField(primary_key=True, serialize=False)),
                ('costo_transporte', models.BigIntegerField()),
                ('comision_empresa', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proceso_venta_local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionLocal',
            fields=[
                ('id_region', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'region_local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteEx',
            fields=[
                ('id_reporte', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1000)),
                ('id_pagoe', models.BigIntegerField()),
            ],
            options={
                'db_table': 'reporte_ex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteLocal',
            fields=[
                ('id_reporte', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'reporte_local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompraExt',
            fields=[
                ('id_solicitud', models.BigAutoField(primary_key=True, serialize=False)),
                ('presupuesto', models.BigIntegerField()),
                ('id_producto', models.BigIntegerField()),
            ],
            options={
                'db_table': 'solicitud_compra_ext',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id_subasta', models.BigAutoField(primary_key=True, serialize=False)),
                ('costo_transporte', models.BigIntegerField()),
            ],
            options={
                'db_table': 'subasta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransporteFinal',
            fields=[
                ('id_transf', models.BigAutoField(primary_key=True, serialize=False)),
                ('seguro', models.CharField(max_length=2)),
                ('coste_seguro', models.BigIntegerField()),
            ],
            options={
                'db_table': 'transporte_final',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('rut_transportista', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_transportista', models.CharField(max_length=25)),
                ('apellido_transportista', models.CharField(max_length=25)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'transportista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('capacidad', models.BigIntegerField()),
                ('refigeracion', models.CharField(max_length=2)),
                ('tamanio', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Bodega',
        ),
        migrations.DeleteModel(
            name='Boleta',
        ),
        migrations.DeleteModel(
            name='Buque',
        ),
        migrations.RemoveField(
            model_name='clientelocal',
            name='id_cli',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
        migrations.DeleteModel(
            name='Consultor',
        ),
        migrations.DeleteModel(
            name='ContratoCliente',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Ganancia',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='ProceVenta',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.RemoveField(
            model_name='relation11',
            name='produ_dispo_id_prod_dispo',
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
        migrations.DeleteModel(
            name='Seguro',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='SolicitudCompra',
        ),
        migrations.DeleteModel(
            name='Transpor',
        ),
        migrations.DeleteModel(
            name='Transporte',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ClienteLocal',
        ),
        migrations.DeleteModel(
            name='ProductoDisp',
        ),
        migrations.DeleteModel(
            name='Relation11',
        ),
    ]
