# Generated by Django 3.1.1 on 2020-09-12 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id_fruta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_fruta', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fruta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productodispserv',
            fields=[
                ('produ_dispo_id_prod_dispo', models.OneToOneField(db_column='produ_dispo_id_prod_dispo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='produfk', serialize=False, to='core.productodisp')),
            ],
            options={
                'db_table': 'productodispserv',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Relation11',
        ),
    ]
