# Generated by Django 3.1.1 on 2020-10-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_direccionlocal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorEstadoExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_ext_valor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_ext',
                'managed': False,
            },
        ),
    ]
