# Generated by Django 3.1.1 on 2020-10-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_valorestadoext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValorEstadoExt',
        ),
    ]
